name: ci.yml
on:
  pull_request:
    branches: ["main"]

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - run: mvn clean compile

      - name: run checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          checkstyle_config: 'google_checks.xml'
          level: error
